### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by coffeegist** [thadeusb/flask-cache#163]
After running for a few hours, this always happens.

Anyone ever ran into this?

```
2017-01-25 01:15:57,442 - flask_cache - ERROR - Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask_cache/__init__.py", line 528, in decorated_function
  File "/usr/lib64/python2.7/site-packages/flask_cache/__init__.py", line 381, in make_cache_key
  File "/usr/lib64/python2.7/site-packages/flask_cache/__init__.py", line 370, in _memoize_version
  File "/usr/lib64/python2.7/site-packages/werkzeug/contrib/cache.py", line 175, in set_many
  File "/usr/lib64/python2.7/site-packages/werkzeug/contrib/cache.py", line 660, in set
  File "/usr/lib64/python2.7/site-packages/werkzeug/contrib/cache.py", line 603, in _prune
  File "/usr/lib64/python2.7/site-packages/werkzeug/contrib/cache.py", line 599, in _list_dir
OSError: [Errno 24] Too many open files: '/var/user/web/flasky.cache'
```

**Comment by coffeegist** [comment]
This was due to running flask with the Werkzeug development server. The dev server wasn't properly letting go of socket fd's, (while using Flask-SocketIO) causing the open file count to get way too large for the application.
