### ISSUE TITLE
report warning/error  when run flask-cache

### ISSUE THREAD

**Issue by wanghaiqing2015** [thadeusb/flask-cache#171]
c:\python27\lib\site-packages\flask_cache\jinja2ext.py:33: ExtDeprecationWarning: Importing flask.ext.cache is deprecated, use flask_cache instead.

===============================================
report error when use pyinstaller to freeze flask project
>>>>>>
C:\Users\root\Desktop\flask-aim-angle\flask_aim\dist\master>master.exe
Traceback (most recent call last):
  File "flask-aim-angle\flask_aim\master.py", line 12, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "flask-aim-angle\flask_aim\app.py", line 21, in <module>
  File "site-packages\flask_cache\__init__.py", line 121, in __init__
  File "site-packages\flask_cache\__init__.py", line 156, in init_app
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\flask_cache\jinja2ext.py", line 33, in <module>
ImportError: No module named ext.cache
Failed to execute script master

**Comment by wanghaiqing2015** [comment]
use flask-caching now

https://flask-caching.readthedocs.io/en/latest/

https://github.com/thadeusb/flask-cache/issues/156
