### ISSUE TITLE
PicklingError: Can't pickle <class 'flaskext.testing.TestResponse'>

### ISSUE THREAD

**Issue by only-entertainment** [thadeusb/flask-cache#52]
Hi, I have a very simple endpoint like this:

``` python
@app.route('zip-codes/<string:zip_code>', methods=["GET"])
@cache.cached(timeout=50)
def zip_codes(zip_code):
    coords = get_coords_for_zip_code(zip_code)
    return success_response(coords)
```

It hits a DB for a JSON representation of lat/longs for a given zip codes. 

I have a test that fails with the error message:

```
PicklingError: Can't pickle <class 'flaskext.testing.TestResponse'>
```

when using the 'simple' cache backend.

My failing test looks like this:

``` python
@patch('views.get_coords_for_zip_code')
    def test_get_zip_code_polygon(self, get_coords_for_zip_code_mock):
        get_coords_for_zip_code_mock.return_value = {
            "zip_code": '90210',
            "polygons": '[[33,44], [44,33]]'
        }

        response = self.client.get('/zip-codes/90210')
        self.assertEqual(response.status_code, 200)

        self.assertTrue('90210' in response.data)
        self.assertTrue('zip_code' in response.data)
        self.assertTrue('polygons' in response.data)
```

Full stack trace:

```
Traceback (most recent call last):
  File "/opt/dealer-portal/tests/blueprints/account/views.py", line 816, in test_get_zip_code_polygon_bad_request
    response = self.client.get('/zip-codes/-1')
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Werkzeug-0.8.2-py2.7.egg/werkzeug/test.py", line 735, in get
    return self.open(*args, **kw)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg/flask/testing.py", line 102, in open
    follow_redirects=follow_redirects)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Werkzeug-0.8.2-py2.7.egg/werkzeug/test.py", line 675, in open
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Werkzeug-0.8.2-py2.7.egg/werkzeug/test.py", line 818, in run_wsgi_app
    app_iter = app(environ, start_response)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg/flask/app.py", line 1518, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg/flask/app.py", line 1506, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg/flask/app.py", line 1504, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg/flask/app.py", line 1264, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg/flask/app.py", line 1262, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask-0.8-py2.7.egg/flask/app.py", line 1248, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Flask_Cache-0.10.1-py2.7.egg/flask_cache/__init__.py", line 218, in decorated_function
    timeout=decorated_function.cache_timeout)
  File "/home/kris/.virtualenvs/dp/local/lib/python2.7/site-packages/Werkzeug-0.8.2-py2.7.egg/werkzeug/contrib/cache.py", line 258, in set
    pickle.HIGHEST_PROTOCOL))
PicklingError: Can't pickle <class 'flaskext.testing.TestResponse'>: attribute lookup flaskext.testing.TestResponse failed
```

Is this a known limitation or a bug?

Thanks!

**Comment by thadeusb** [comment]
Looks like a problem with the testing library you are using. To my knowledge it is not possible to pickle mock objects (limitation in the pickle library), you might need some way to convert the mock object to a real python object so that it can be pickled, or disable caching for your unit tests by using NullCache, or override the werkzeug caching objects to use something other than pickle for serialization.

**Comment by only-entertainment** [comment]
Thanks for the quick response and for the great library! You are right, it is not possible to pickle mock objects. Using the NullCache backend for my tests satisfied what I was trying to accomplish.
